app:
    resource: '@AppBundle/Controller/'
    type:     annotation
mail:
    resource: '@AppBundle/Controller/Mail/'
    type:     annotation
    prefix:   /mail
login:
    path: /login
    methods: [ get ]
    defaults:  { _controller: AppBundle:Auth:login }
logout:
    path: /logout
    methods: [ get, post ]
